require 'parsers/parse_eligibility'
class EligibilityApi
	def send(params)
		params = {
			:api_key=>"TneErbrxyRnO1M1q4G8zrvqzArl79mugZSHW", 
			:payer_id=>params['payer_id'], :provider_npi=>params['p_npi'], 
			:provider_first_name=>params['p_first_name'], 
			:provider_last_name=>params['p_last_name'], :member_id=>params['ins_id'], :member_first_name=>params['first_name'], :member_last_name=>params['last_name'], :member_dob=>params['dob'], :service_type=>params['service_type'], :procedure_code=>params['procedure_code'], :multiple_stc=>true} 
		begin
			current_json_string = RestClient.get("https://gds.eligibleapi.com/v1.4/coverage/all.json", params: params)
			if current_json_string.present? && JSON.parse(current_json_string)['error'].present?
				return error = JSON.parse(current_json_string)['error']
			end
		rescue Exception=>e 
			error = JSON.parse(e.response)['error']['response_code']
		end	
		
		if error.present? && error = 'Y'
			begin
				current_json_string = RestClient.get("https://gds.eligibleapi.com/v1.4/coverage/medicare.json", params: params)
				if current_json_string.present? && JSON.parse(current_json_string)['error'].present?
					return error = JSON.parse(current_json_string)['error']
				end
				
			rescue Exception=>e 
				return JSON.parse(e.response)
			end	
			
			
			current_array = JSON.parse(current_json_string)
			return ParseEligibility.new.get_medicare_json(current_array)
		
		else
			return current_array = JSON.parse(current_json_string)
			 ParseEligibility.new.get_coverage_json(current_array)
		end
	end

	def service_type_codes
		{
			"None" => nil,
			"Medical Care"=>"1",
			 "Surgical"=>"2",
			 "Consultation"=>"3",
			 "Diagnostic X-Ray"=>"4",
			 "Diagnostic Lab"=>"5",
			 "Radiation Therapy"=>"6",
			 "Anesthesia"=>"7",
			 "Surgical Assistance"=>"8",
			 "Other Medical"=>"9",
			 "Blood Charges"=>"10",
			 "Used Durable Medical Equipment"=>"11",
			 "Durable Medical Equipment Purchase"=>"12",
			 "Ambulatory Service Center Facility"=>"13",
			 "Renal Supplies in the Home"=>"14",
			 "Alternate Method Dialysis"=>"15",
			 "Chronic Renal Disease (CRD) Equipment"=>"16",
			 "Pre-Admission Testing"=>"17",
			 "Durable Medical Equipment Rental"=>"18",
			 "Pneumonia Vaccine"=>"19",
			 "Second Surgical Opinion"=>"20",
			 "Third Surgical Opinion"=>"21",
			 "Social Work"=>"22",
			 "Diagnostic Dental"=>"23",
			 "Periodontics"=>"24",
			 "Restorative"=>"25",
			 "Endodontics"=>"26",
			 "Maxillofacial Prosthetics"=>"27",
			 "Adjunctive Dental Services"=>"28",
			 "Health Benefit Plan Coverage"=>"30",
			 "Benefit Disclaimer"=>"31",
			 "Plan Waiting Period"=>"32",
			 "Chiropractic"=>"33",
			 "Chiropractic Office Visits"=>"34",
			 "Dental Care"=>"35",
			 "Dental Crowns"=>"36",
			 "Dental Accident"=>"37",
			 "Orthodontics"=>"38",
			 "Prosthodontics"=>"39",
			 "Oral Surgery"=>"40",
			 "Routine Preventive Dental"=>"41",
			 "Home Health Care"=>"42",
			 "Home Health Prescriptions"=>"43",
			 "Home Health Visits"=>"44",
			 "Hospice"=>"45",
			 "Respite Care"=>"46",
			 "Hospital"=>"47",
			 "Hospital - Inpatient"=>"48",
			 "Hospital - Room and Board"=>"49",
			 "Hospital - Outpatient"=>"50",
			 "Hospital - Emergency Accident"=>"51",
			 "Hospital - Emergency Medical"=>"52",
			 "Hospital - Ambulatory Surgical"=>"53",
			 "Long Term Care"=>"54",
			 "Major Medical"=>"55",
			 "Medically Related Transportation"=>"56",
			 "Air Transportation"=>"57",
			 "Cabulance"=>"58",
			 "Licensed Ambulance"=>"59",
			 "General Benefits"=>"60",
			 "In-vitro Fertilization"=>"61",
			 "MRI/CAT Scan"=>"62",
			 "Donor Procedure"=>"63",
			 "Acupuncture"=>"64",
			 "Newborn Care"=>"65",
			 "Pathology"=>"66",
			 "Smoking Cessation"=>"67",
			 "Well Baby Care"=>"68",
			 "Maternity"=>"69",
			 "Transplants"=>"70",
			 "Audiology Exam"=>"71",
			 "Inhalation Therapy"=>"72",
			 "Diagnostic Medical"=>"73",
			 "Private Duty Nursing"=>"74",
			 "Prosthetic Device"=>"75",
			 "Dialysis"=>"76",
			 "Otological Exam"=>"77",
			 "Chemotherapy"=>"78",
			 "Allergy Testing"=>"79",
			 "Immunizations"=>"80",
			 "Routine Physical"=>"81",
			 "Family Planning"=>"82",
			 "Infertility"=>"83",
			 "Abortion"=>"84",
			 "HIV - AIDS Treatment"=>"85",
			 "Emergency Services"=>"86",
			 "Cancer Treatment"=>"87",
			 "Pharmacy"=>"88",
			 "Free Standing Prescription Drug"=>"89",
			 "Mail Order Prescription Drug"=>"90",
			 "Brand Name Prescription Drug"=>"91",
			 "Generic Prescription Drug"=>"92",
			 "Podiatry"=>"93",
			 "Podiatry - Office Visits"=>"94",
			 "Podiatry - Nursing Home Visits"=>"95",
			 "Professional (Physician)"=>"96",
			 "Anesthesiologist"=>"97",
			 "Professional (Physician) Visit - Office"=>"98",
			 "Professional (Physician) Visit - Inpatient"=>"99",
			 "Professional (Physician) Visit - Outpatient"=>"A0",
			 "Professional (Physician) Visit - Nursing Home"=>"A1",
			 "Professional (Physician) Visit - Skilled Nursing Facility"=>"A2",
			 "Professional (Physician) Visit - Home"=>"A3",
			 "Psychiatric"=>"A4",
			 "Psychiatric - Room and Board"=>"A5",
			 "Psychotherapy"=>"A6",
			 "Psychiatric - Inpatient"=>"A7",
			 "Psychiatric - Outpatient"=>"A8",
			 "Rehabilitation"=>"A9",
			 "Rehabilitation - Room and Board"=>"AA",
			 "Rehabilitation - Inpatient"=>"AB",
			 "Rehabilitation - Outpatient"=>"AC",
			 "Occupational Therapy"=>"AD",
			 "Physical Medicine"=>"AE",
			 "Speech Therapy"=>"AF",
			 "Skilled Nursing Care"=>"AG",
			 "Skilled Nursing Care - Room and Board"=>"AH",
			 "Substance Abuse"=>"AI",
			 "Alcoholism Treatment"=>"AJ",
			 "Drug Addiction"=>"AK",
			 "Optometry Vision"=>"AL",
			 "Frames"=>"AM",
			 "Routine Exam"=>"AN",
			 "Lenses"=>"AO",
			 "Routine Eye Exam"=>"AP",
			 "Nonmedically Necessary Physical"=>"AQ",
			 "Experimental Drug Therapy"=>"AR",
			 "Burn Care"=>"B1",
			 "Brand Name Prescription Drug - Formulary"=>"B2",
			 "Brand Name Prescription Drug - Non-Formulary"=>"B3",
			 "Independent Medical Evaluation"=>"BA",
			 "Psychiatric Treatment Partial Hospitalization"=>"BB",
			 "Day Care (Psychiatric)"=>"BC",
			 "Cognitive Therapy"=>"BD",
			 "Massage Therapy"=>"BE",
			 "Pulmonary Rehabilitation"=>"BF",
			 "Cardiac Rehabilitation"=>"BG",
			 "Pediatric"=>"BH",
			 "Nursery Room and Board"=>"BI",
			 "Skin"=>"BJ",
			 "Orthopedic"=>"BK",
			 "Cardiac"=>"BL",
			 "Lymphatic"=>"BM",
			 "Gastrointestinal"=>"BN",
			 "Endocrine"=>"BP",
			 "Neurology"=>"BQ",
			 "Eye"=>"BR",
			 "Invasive Procedures"=>"BS",
			 "Gynecological"=>"BT",
			 "Obstetrical"=>"BU",
			 "Obstetrical/Gynecological"=>"BV",
			 "Mail Order Prescription Drug: Brand Name"=>"BW",
			 "Mail Order Prescription Drug: Generic"=>"BX",
			 "Physician Visit - Sick"=>"BY",
			 "Physician Visit - Well"=>"BZ",
			 "Coronary Care"=>"C1",
			 "Private Duty Nursing - Inpatient"=>"CA",
			 "Private Duty Nursing - Home"=>"CB",
			 "Surgical Benefits - Professional (Physician)"=>"CC",
			 "Surgical Benefits - Facility"=>"CD",
			 "Mental Health Provider - Inpatient"=>"CE",
			 "Mental Health Provider - Outpatient"=>"CF",
			 "Mental Health Facility - Inpatient"=>"CG",
			 "Mental Health Facility - Outpatient"=>"CH",
			 "Substance Abuse Facility - Inpatient"=>"CI",
			 "Substance Abuse Facility - Outpatient"=>"CJ",
			 "Screening X-ray"=>"CK",
			 "Screening laboratory"=>"CL",
			 "Mammogram: High Risk Patient"=>"CM",
			 "Mammogram: Low Risk Patient"=>"CN",
			 "Flu Vaccination"=>"CO",
			 "Eyewear Accessories"=>"CP",
			 "Case Management"=>"CQ",
			 "Dermatology"=>"DG",
			 "Durable Medical Equipment"=>"DM",
			 "Diabetic Supplies"=>"DS",
			 "Generic Prescription Drug - Formulary"=>"GF",
			 "Generic Prescription Drug - Non-Formulary"=>"GN",
			 "Allergy"=>"GY",
			 "Intensive Care"=>"IC",
			 "Mental Health"=>"MH",
			 "Neonatal Intensive Care"=>"NI",
			 "Oncology"=>"ON",
			 "Physical Therapy"=>"PT",
			 "Pulmonary"=>"PU",
			 "Renal"=>"RN",
			 "Residential Psychiatric treatment"=>"RT",
			 "Transitional Care"=>"TC",
			 "Transitional Nursery Care"=>"TN",
			 "Urgent Care"=>"UC",
			 "Specialist"=>"SP"
			}

	end

	def procedure_codes
		{
	'None' => nil,		
	'Screening Mammography (MAMM)' => '77057',
	'Cardiovascular Disease Screening (CARD)' => '80061',
	'Fecal Occult Blood Test (FOBT)' => '82270',
	'Cardiovascular Disease Screening (CARD)' => '82465',
	'Diabetes Screening Tests (DIAB)' => '82947',
	'Diabetes Screening Tests (DIAB)' => '82950',
	'Diabetes Screening Tests (DIAB)' => '82951',
	'Cardiovascular Disease Screening (CARD)' => '83718',
	'Cardiovascular Disease Screening (CARD)' => '84478',
	'Pneumococcal Vaccine (PPV)' => '90669',
	'Pneumococcal Vaccine (PPV)' => '90670',
	'Pneumococcal Vaccine (PPV)' => '90732',
	'Screening Pelvic Exam (PCBE)' => 'G0101',
	'Prostate Cancer Screening (PROS) i' => 'G0102',
	'Prostate Cancer Screening (PROS) i' => 'G0103',
	'Colorectal Cancer Screening (COLO)' => 'G0104',
	'Colorectal Cancer Screening (COLO)' => 'G0105',
	'Colorectal Cancer Screening (COLO)' => 'G0106',
	'Glaucoma Screening (GLAU)' => 'G0117',
	'Glaucoma Screening (GLAU)' => 'G0118',
	'Colorectal Cancer Screening (COLO)' => 'G0120',
	'Colorectal Cancer Screening (COLO)' => 'G0121',
	'Screening Pap Test (PAPT)' => 'G0123',
	'Screening Pap Test (PAPT)' => 'G0143',
	'Screening Pap Test (PAPT)' => 'G0144',
	'Screening Pap Test (PAPT)' => 'G0145',
	'Screening Pap Test (PAPT)' => 'G0147',
	'Screening Pap Test (PAPT)' => 'G0148',
	'Screening Mammography (MAMM)' => 'G0202',
	'Fecal Occult Blood Test (FOBT)' => 'G0328',
	'Ultrasound Screening for Abdominal Aortic Aneurysm (AAA)' => 'G0389',
	'Initial Preventive Physical Examination (IPPE)' => 'G0402',
	'Initial Preventive Physical Examination (IPPE)' => 'G0403',
	'Initial Preventive Physical Examination (IPPE)' => 'G0404',
	'Initial Preventive Physical Examination (IPPE)' => 'G0405',
	'Annual Wellness Visit (AWV)' => 'G0438',
	'Annual Wellness Visit (AWV)' => 'G0439',
	'Annual Depression Screening' => 'G0444',
	'Screening and High Intensive Behavioral Counseling (HIBC) to prevent STIs' => 'G0445',
	'Intensive Behavioral Therapy (IBT) for Cardiovascular Disease (CVD)' => 'G0446',
	'Intensive Behavioral Counseling for Obesity' => 'G0447',
	'Screening Pap Test (PAPT)' => 'P3000',
	'Screening Pap Test (PAPT)' => 'Q0091',
		}
	end
end
# params = {
# :api_key=>"TneErbrxyRnO1M1q4G8zrvqzArl79mugZSHW", 
# :payer_id=>"ILBLS", :provider_npi=>"1881868669", 
# :provider_first_name=>"Andy", 
# :provider_last_name=>"Stroud", :member_id=>"XOF823201728", :member_first_name=>"Howard", :member_last_name=>"Goldsmith", :member_dob=>"1989-10-17", :service_type=>"98", :procedure_code=>'84478', :multiple_stc=>true} 

# http://screencast.com/t/yI7Z5NJed
